name: Decodable Flink CI
on:
  - pull_request
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Fetch AWS CodeArtifact token
        run: echo CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain decodable --domain-owner 671293015970 --query authorizationToken --duration-seconds 3600 --output text ) >> $GITHUB_ENV
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "decodable-mvn-releases-local",
                "username": "aws",
                "password": "${env.CODEARTIFACT_AUTH_TOKEN}"
              },
            {
              "id": "decodable-mvn-snapshots-local",
              "username": "aws",
              "password": "${env.CODEARTIFACT_AUTH_TOKEN}"
            }
            ]
      - name: Build
        run: ./mvnw clean install -B -DskipTests -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
      - name: Flink Version
        run: echo "FLINK_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Decodable Flink Dist Name
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "FLINK_DIST_NAME=decodable-flink-${{ env.FLINK_VERSION }}-$git_hash.tgz" >> $GITHUB_ENV
      - name: Decodable Flink dist
        # if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/decodable') }}
        run: |
          set -x
          TARGET="ci-build"
          if [[ "${{ github.ref_name }}" =~ ^decodable.* ]]; then
            TARGET="dist"
          fi
          tar -czf ${{ github.workspace }}/${{ env.FLINK_DIST_NAME }} -C ${{ github.workspace }}/build-target/ .
          aws s3 cp ${{ github.workspace }}/${{ env.FLINK_DIST_NAME }} s3://decodable-flink-dist/${TARGET}/${{ github.ref_name }}/
      - name: Deploy maven artifacts
        # if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/decodable') }}
        run: ./mvnw deploy -DskipTests
